export const imagesMetadata = {
  'File:FileName': 'PIA18906.jpg',
  'EXIF:ColorSpace': 'Uncalibrated',
  'JFIF:YResolution': 1,
  'AVAIL:MediaType': 'image',
  'File:FilePermissions': 'rw-rw-r--',
  'File:ColorComponents': 3,
  'File:CurrentIPTCDigest': 'f8ac561c7e9676236580708de3eeb3b1',
  SourceFile: './tmp2/PIA18906.jpg',
  'EXIF:FlashpixVersion': '0100',
  'File:FileTypeExtension': 'jpg',
  'AVAIL:NASAID': 'PIA18906',
  'File:MIMEType': 'image/jpeg',
  'JFIF:XResolution': 1,
  'File:YCbCrSubSampling': 'YCbCr4:2:0 2 2',
  'File:BitsPerSample': 8,
  'EXIF:ResolutionUnit': 'None',
  'XMP:DateCreated': '2014:12:22 18:53:13',
  'XMP:Credit': 'NASA/JPL-Caltech/GSFC',
  'EXIF:ExifVersion': '0230',
  'AVAIL:Keywords': ['Sun', 'NuSTAR'],
  'File:FileAccessDate': '2015:12:23 19:00:50-08:00',
  'File:ImageWidth': 3150,
  'AVAIL:Title': 'Sun Shines in High-Energy X-rays',
  'XMP:Description':
    'X-rays stream off the sun in this first picture of the sun, overlaid on a picture taken by NASA Solar Dynamics Observatory SDO, taken by NASA NuSTAR. The field of view covers the west limb of the sun.',
  'XMP:Center': 'JPL',
  'EXIF:YCbCrPositioning': 'Centered',
  'EXIF:ComponentsConfiguration': 'Y, Cb, Cr, -',
  'EXIF:CreateDate': '2014:12:22 18:53:13',
  'AVAIL:Owner': '',
  'AVAIL:Description508':
    'X-rays stream off the sun in this first picture of the sun, overlaid on a picture taken by NASA Solar Dynamics Observatory SDO, taken by NASA NuSTAR. The field of view covers the west limb of the sun.',
  'File:ExifByteOrder': 'Big-endian Motorola, MM',
  'AVAIL:Center': 'JPL',
  'AVAIL:Photographer': '',
  'JFIF:JFIFVersion': 1.01,
  'Composite:ImageSize': '3150x1600',
  'File:Directory': './tmp2',
  'EXIF:YResolution': 1,
  'AVAIL:SecondaryCreator': 'NASA/JPL-Caltech/GSFC',
  'XMP:Nasa_id': 'PIA18906',
  'EXIF:XResolution': 1,
  'File:FileInodeChangeDate': '2015:12:23 19:00:50-08:00',
  'File:FileSize': '281 kB',
  'XMP:Createdate': '2014:12:22 18:53:13',
  'XMP:ImageDescription':
    'X-rays stream off the sun in this first picture of the sun, overlaid on a picture taken by NASA Solar Dynamics Observatory SDO, taken by NASA NuSTAR. The field of view covers the west limb of the sun.',
  'EXIF:ImageDescription':
    'X-rays stream off the sun in this first picture of the sun, overlaid on a picture taken by NASA Solar Dynamics Observatory SDO, taken by NASA NuSTAR. The field of view covers the west limb of the sun.',
  'AVAIL:Album': '',
  'ExifTool:ExifToolVersion': 10.05,
  'XMP:XMPToolkit': 'Image::ExifTool 10.05',
  'AVAIL:Description':
    'X-rays stream off the sun in this first picture of the sun, overlaid on a picture taken by NASA Solar Dynamics Observatory SDO, taken by NASA NuSTAR. The field of view covers the west limb of the sun.',
  'XMP:CreateDate': '2014:12:22 18:53:13',
  'AVAIL:Location': '',
  'IPTC:Keywords': ['Sun', 'NuSTAR'],
  'File:FileModifyDate': '2015:12:23 19:00:50-08:00',
  'AVAIL:DateCreated': '2014:12:22 18:53:13',
  'Composite:Megapixels': 5.0,
  'XMP:Title': 'Sun Shines in High-Energy X-rays',
  'IPTC:ApplicationRecordVersion': 4,
  'File:EncodingProcess': 'Baseline DCT, Huffman coding',
  'XMP:Source': 'NASA/JPL-Caltech/GSFC',
  'File:ImageHeight': 1600,
  'File:FileType': 'JPEG',
  'JFIF:ResolutionUnit': 'None',
};
