export const videoMetadata = {
  'AVAIL:Keywords': [
    'NASA',
    'Marshall Space Flight Center',
    'MSFC',
    'Hinode',
    'x-ray telescope',
    'sun',
    'solar flare',
  ],
  'File:FileAccessDate': '2017:09:26 20:06:44+00:00',
  'AVAIL:Description508':
    'On Sept. 10, 2017, the Hinode satellite observed an enormous X-class flare burst from an active region on the western edge of the Sun.',
  'QuickTime:MinorVersion': '0.2.0',
  'QuickTime:VideoFrameRate': 10,
  'QuickTime:Duration': '0:00:36',
  'QuickTime:OpColor': '0 0 0',
  'QuickTime:MediaModifyDate': '0000:00:00 00:00:00',
  'QuickTime:ImageHeight': 510,
  'QuickTime:MediaHeaderVersion': 0,
  'QuickTime:MediaCreateDate': '0000:00:00 00:00:00',
  'AVAIL:MediaType': 'video',
  'QuickTime:MajorBrand': 'MP4  Base Media v1 [IS0 14496-12:2003]',
  'QuickTime:MediaLanguageCode': 'und',
  'QuickTime:HandlerDescription': 'VideoHandler',
  'QuickTime:TrackModifyDate': '0000:00:00 00:00:00',
  SourceFile: '/tmp/tmp7yrjeeof',
  'QuickTime:CurrentTime': '0 s',
  'QuickTime:PreviewDuration': '0 s',
  'QuickTime:ModifyDate': '0000:00:00 00:00:00',
  'AVAIL:SecondaryCreator':
    'JAXA/NASA/Smithsonian Astrophysical Observatory/Montana State University',
  'AVAIL:NASAID': 'XRT20170910_Al_poly_noaxis',
  'AVAIL:Owner': 'lmohon',
  'AVAIL:Location': 'Sun',
  'QuickTime:TrackLayer': 0,
  'AVAIL:Photographer': 'JAXA/NASA/Smithsonian Astrophysical Observatory/Montana State University',
  'QuickTime:CreateDate': '0000:00:00 00:00:00',
  'QuickTime:TrackHeaderVersion': 0,
  'File:FileInodeChangeDate': '2017:09:26 20:06:45+00:00',
  'QuickTime:PosterTime': '0 s',
  'QuickTime:SourceImageWidth': 690,
  'QuickTime:TrackDuration': '0:00:36',
  'QuickTime:ImageWidth': 690,
  'QuickTime:TrackID': 1,
  'QuickTime:MovieDataSize': 10491916,
  'QuickTime:NextTrackID': 2,
  'AVAIL:Album': '',
  'AVAIL:DateCreated': '10 September 2017',
  'QuickTime:MediaDuration': '0:00:36',
  'File:FileName': 'tmp7yrjeeof',
  'QuickTime:SelectionDuration': '0 s',
  'QuickTime:TrackVolume': '0.00%',
  'QuickTime:Encoder': 'Lavf56.40.101',
  'QuickTime:PreferredVolume': '100.00%',
  'File:FileType': 'MP4',
  'QuickTime:SelectionTime': '0 s',
  'ExifTool:ExifToolVersion': 10.05,
  'QuickTime:BitDepth': 24,
  'QuickTime:HandlerVendorID': 'Apple',
  'File:Directory': '/tmp',
  'Composite:Megapixels': 0.352,
  'QuickTime:YResolution': 72,
  'Composite:Rotation': 0,
  'File:MIMEType': 'video/mp4',
  'QuickTime:MovieDataOffset': 48,
  'QuickTime:HandlerType': 'Metadata',
  'AVAIL:Title': 'Hinode Takes an X-Ray of a Powerful Solar Flare',
  'QuickTime:GraphicsMode': 'srcCopy',
  'AVAIL:Description':
    "On Sept. 10, 2017, the Hinode satellite observed an enormous X-class flare burst from an active region on the western edge of the Sun. The video shows the high-energy flare as seen by Hinode's X-Ray Telescope. The emission was so bright that the initial blast caused the detector to saturate. The giant explosion sent a huge cloud of superhot plasma zooming into interplanetary space -- a phenomenon known as a coronal mass ejection. Studying large flares like this one with a variety of instruments is key to understanding exactly what causes these dramatic eruptions, and one day predicting them before they occur.",
  'AVAIL:Creator': null,
  'File:FilePermissions': 'rw-------',
  'File:FileTypeExtension': 'mp4',
  'QuickTime:MatrixStructure': '1 0 0 0 1 0 0 0 1',
  'File:FileModifyDate': '2017:09:26 20:06:45+00:00',
  'QuickTime:TimeScale': 1000,
  'AVAIL:Center': 'MSFC',
  'QuickTime:CompressorID': 'avc1',
  'QuickTime:PreferredRate': 1,
  'QuickTime:CompatibleBrands': ['isom', 'iso2', 'avc1', 'mp41'],
  'QuickTime:XResolution': 72,
  'QuickTime:MovieHeaderVersion': 0,
  'QuickTime:MediaTimeScale': 10240,
  'Composite:ImageSize': '690x510',
  'Composite:AvgBitrate': '2.31 Mbps',
  'QuickTime:PreviewTime': '0 s',
  'QuickTime:SourceImageHeight': 510,
  'File:FileSize': '10 MB',
  'QuickTime:TrackCreateDate': '0000:00:00 00:00:00',
};
